server:
  servlet:
    context-path: /customer
  port: 8073
resilience4j:
  circuitbreaker:
    instances:
      customerContactToBankService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
        timeoutDuration: 2s
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
spring:
  data:
    mongodb:
      uri: mongodb+srv://Luis:Rf1a76Py1s5dt7Dl@projectweek01.mxgyr.mongodb.net/BootCampWeek01?retryWrites=true&w=majority
  application:
    name: customerservice
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
  instance:
    prefer-ip-address: true
    hostname: ${COMPUTERNAME:localhost}  
bank-api:
  base-url: http://localhost:8080
